/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'iconoir:accessibility-sign',
      order: 100
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base$view.log',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      icon: 'line-md:cake',
      order: 7
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['Q_SUPER']
    },
    children: [
      {
        name: 'manage_channel',
        path: '/manage/channel',
        component: 'view.manage_channel',
        meta: {
          title: 'manage_channel',
          i18nKey: 'route.manage_channel',
          icon: 'material-symbols:route',
          order: 1
        }
      },
      {
        name: 'manage_token',
        path: '/manage/token',
        component: 'view.manage_token',
        meta: {
          title: 'manage_token',
          i18nKey: 'route.manage_token',
          icon: 'carbon:user-role',
          order: 2
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 2
        }
      }
    ]
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting',
      icon: 'grommet-icons:apps-rounded',
      roles: ['Q_SUPER'],
      order: 10
    },
    children: [
      {
        name: 'setting_other',
        path: '/setting/other',
        component: 'view.setting_other',
        meta: {
          title: 'setting_other',
          i18nKey: 'route.setting_other',
          icon: 'ic:round-construction'
        },
        order: 7
      }
    ]
  },
  {
    name: 'tariffs',
    path: '/tariffs',
    component: 'layout.base$view.tariffs',
    meta: {
      title: 'tariffs',
      i18nKey: 'route.tariffs',
      icon: 'line-md:bell-twotone-loop',
      order: 8
    }
  },
  {
    name: 'topup',
    path: '/topup',
    component: 'layout.base$view.topup',
    meta: {
      title: 'topup',
      i18nKey: 'route.topup',
      order: 6,
      icon: 'line-md:medical-services-twotone'
    }
  }
];
